//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngxFrmsWebApi.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FrmsEntities : DbContext
    {
        public FrmsEntities()
            : base("name=FrmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ref_FilingRequestStatus> ref_FilingRequestStatus { get; set; }
        public virtual DbSet<ref_FilingRequestType> ref_FilingRequestType { get; set; }
        public virtual DbSet<ref_StateFilingRequirementType> ref_StateFilingRequirementType { get; set; }
        public virtual DbSet<ref_StateFilingStatus> ref_StateFilingStatus { get; set; }
        public virtual DbSet<trn_FilingRequest> trn_FilingRequest { get; set; }
        public virtual DbSet<trn_FilingRequestCarrierXref> trn_FilingRequestCarrierXref { get; set; }
        public virtual DbSet<trn_FilingRequestPolicyTypeXref> trn_FilingRequestPolicyTypeXref { get; set; }
        public virtual DbSet<trn_FilingRequestReplaceFormXref> trn_FilingRequestReplaceFormXref { get; set; }
        public virtual DbSet<trn_FormFilingRequest> trn_FormFilingRequest { get; set; }
        public virtual DbSet<trn_FormFilingRequestFormGroupXref> trn_FormFilingRequestFormGroupXref { get; set; }
        public virtual DbSet<trn_StateFiling> trn_StateFiling { get; set; }
    }
}
