//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngxFrmsWebApi.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_FilingRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trn_FilingRequest()
        {
            this.trn_FilingRequestReplaceFormXref = new HashSet<trn_FilingRequestReplaceFormXref>();
            this.trn_FilingRequestCarrierXref = new HashSet<trn_FilingRequestCarrierXref>();
            this.trn_FilingRequestPolicyTypeXref = new HashSet<trn_FilingRequestPolicyTypeXref>();
            this.trn_FormFilingRequest = new HashSet<trn_FormFilingRequest>();
            this.trn_StateFiling = new HashSet<trn_StateFiling>();
        }
    
        public int FilingRequestId { get; set; }
        public int FilingRequestTypeId { get; set; }
        public int FilingRequestStatusId { get; set; }
        public string SubmittedBy { get; set; }
        public System.DateTime SubmittedDate { get; set; }
        public int PolicyClassId { get; set; }
        public string Subject { get; set; }
        public string ComplianceFilingNumber { get; set; }
        public string ListItemId { get; set; }
        public string ListId { get; set; }
        public string TaskListId { get; set; }
        public string HistoryListId { get; set; }
        public string WorkflowId { get; set; }
        public Nullable<int> RequestedById { get; set; }
        public System.DateTime AuditLastModified { get; set; }
        public string AuditLastModifiedBy { get; set; }
        public Nullable<int> SystemAffected { get; set; }
        public Nullable<int> RequestPriority { get; set; }
        public string PriorityJustification { get; set; }
        public Nullable<bool> BlockRelease { get; set; }
        public string BlockReleaseReason { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public string StatusComments { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ref_FilingRequestStatus ref_FilingRequestStatus { get; set; }
        public virtual ref_FilingRequestType ref_FilingRequestType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_FilingRequestReplaceFormXref> trn_FilingRequestReplaceFormXref { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_FilingRequestCarrierXref> trn_FilingRequestCarrierXref { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_FilingRequestPolicyTypeXref> trn_FilingRequestPolicyTypeXref { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_FormFilingRequest> trn_FormFilingRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_StateFiling> trn_StateFiling { get; set; }
    }
}
