//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngxFrmsWebApi.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_FormFilingRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trn_FormFilingRequest()
        {
            this.trn_FormFilingRequestFormGroupXref = new HashSet<trn_FormFilingRequestFormGroupXref>();
        }
    
        public int FormFilingRequestId { get; set; }
        public int FilingRequestId { get; set; }
        public int DocumentTypeId { get; set; }
        public int CountryId { get; set; }
        public Nullable<int> FormClassId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string FormIdString { get; set; }
        public string BaseFormIdString { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> EditionDate { get; set; }
        public string FormType { get; set; }
        public bool CanHaveMultiples { get; set; }
        public string AdobeId { get; set; }
        public int AppliesToSubmission { get; set; }
        public int AppliesToQuote { get; set; }
        public int AppliesToBinder { get; set; }
        public int AppliesToPolicy { get; set; }
        public int AppliesToEndorsement { get; set; }
        public bool IsCommon { get; set; }
        public bool IsPremiumBearing { get; set; }
        public bool IncludeTermsOnQB { get; set; }
        public bool IncludeTermsOnDecPage { get; set; }
        public Nullable<int> SubjectivityFormId { get; set; }
        public string SubjectivityDefaultText { get; set; }
        public Nullable<int> OrderWithinClass { get; set; }
        public string FormDefaultComment { get; set; }
        public string SpecialBehavior { get; set; }
        public string SubCategory { get; set; }
        public bool Broadens { get; set; }
        public bool Restricts { get; set; }
        public bool Clarifies { get; set; }
        public bool WatermarkOnQuote { get; set; }
        public bool WatermarkOnBinder { get; set; }
        public bool WatermarkOnPolicy { get; set; }
        public bool WatermarkOnEndorsement { get; set; }
        public bool HasUserFillIns { get; set; }
        public bool HasSystemFillIns { get; set; }
        public string ChangeDetails { get; set; }
        public string PurposeOfForm { get; set; }
        public string ShortName { get; set; }
        public Nullable<bool> ClaimsApprovalRequired { get; set; }
        public Nullable<bool> IsNewForm { get; set; }
        public Nullable<bool> ReplacesExistingForm { get; set; }
        public Nullable<System.DateTime> ReplacesExisitingFormExpiryDate { get; set; }
        public string ReplacesExistingFormName { get; set; }
        public Nullable<System.DateTime> ReplacesExistingFormEditionDate { get; set; }
        public Nullable<int> RelatedFilingRequest { get; set; }
        public Nullable<bool> Mandatory { get; set; }
        public Nullable<bool> Optional { get; set; }
        public System.DateTime AuditLastModified { get; set; }
        public string AuditLastModifiedBy { get; set; }
        public bool RetainUserFillIns { get; set; }
        public bool IncludeDataOnQuote { get; set; }
        public bool IncludeDataOnBinder { get; set; }
        public bool IncludeDataOnPolicy { get; set; }
        public bool IncludeDataOnEndorsement { get; set; }
        public Nullable<bool> BypassWorkFlow { get; set; }
        public Nullable<System.Guid> NavigateFormEditionID { get; set; }
        public Nullable<System.Guid> ExistingFormsEditionID { get; set; }
        public Nullable<int> UATRejection { get; set; }
        public Nullable<int> ChangeRequest { get; set; }
        public Nullable<int> FormTemplateId { get; set; }
    
        public virtual trn_FilingRequest trn_FilingRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_FormFilingRequestFormGroupXref> trn_FormFilingRequestFormGroupXref { get; set; }
    }
}
