//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngxFrmsWebApi.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_StateFiling
    {
        public int StateFilingId { get; set; }
        public int FilingRequestId { get; set; }
        public Nullable<System.DateTime> FilingDate { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<System.DateTime> NavigateFormEffectiveDate { get; set; }
        public int StateFilingStatusId { get; set; }
        public int StateFilingRequirementTypeId { get; set; }
        public string Comment { get; set; }
        public int StateId { get; set; }
        public Nullable<System.DateTime> AuditLastModified { get; set; }
        public string AuditLastModifiedBy { get; set; }
        public Nullable<int> CarrierID { get; set; }
        public Nullable<System.DateTime> ProductionReleaseDate { get; set; }
    
        public virtual ref_StateFilingRequirementType ref_StateFilingRequirementType { get; set; }
        public virtual ref_StateFilingStatus ref_StateFilingStatus { get; set; }
        public virtual trn_FilingRequest trn_FilingRequest { get; set; }
    }
}
